### ISSUE TITLE
Error setting up entry Configuration.yaml for smappee

### ISSUE THREAD

**Issue by gieljnssns** [smappee/pysmappee#2]
I have another error with the new smappee component after some restarts of HA, I'm seeing this error
```
Logger: homeassistant.config_entries
Source: custom_components/smappee/__init__.py:76
First occurred: 8:25:07 (1 occurrences)
Last logged: 8:25:07

Error setting up entry Configuration.yaml for smappee
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 220, in async_setup
    hass, self
  File "/config/custom_components/smappee/__init__.py", line 76, in async_setup_entry
    await hass.async_add_executor_job(smappee.load_service_locations)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/site-packages/pysmappee/smappee.py", line 19, in load_service_locations
    locations = self.smappee_api.get_service_locations()
  File "/usr/local/lib/python3.7/site-packages/pysmappee/api.py", line 18, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pysmappee/api.py", line 62, in get_service_locations
    r.raise_for_status()
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://app1pub.smappee.net/dev/v3/servicelocation
```

When I remove Smappee from integrations - restart HA - re-add Smappee , it all works again

**Comment by bsmappee** [comment]
The issue should be resolved with PR https://github.com/home-assistant/core/pull/37680 and HA release 0.112.5.
